### ISSUE TITLE
IPinfo DevRel with tips

### ISSUE THREAD

**Issue by abdullahdevrel** [Dancha16/Pet#2]
Hi, I really appreciate you using our API service, which is wonderful. I have a couple of tips as I am quite familiar with the problem you are facing.

### Use the [IPinfo CLI](https://github.com/ipinfo/cli)

The [IPinfo CLI](https://github.com/ipinfo/cli) is an extremely powerful utility that comes with a ton of features. I highly recommend exploring the tool.

https://github.com/ipinfo/cli

In your case, you should use the `grepip` command of the CLI. The `grepip` command can extract IP addresses from any plaintext file. It also comes with a lot of options.

```
Usage: ipinfo grepip [<opts>]

Options:
  General:
    --only-matching, -o
      print only matched IP in result line, excluding surrounding content.
    --include-cidrs
      prints the CIDRs too.
    --include-ranges
      prints the Ranges too.
    --cidrs-only
      prints the CIDRs only.
    --ranges-only
      prints the Ranges only.
    --no-filename, -h
      don't print source of match in result lines when more than 1 source.
    --no-recurse
      don't recurse into more directories in directory sources.
    --help
      show help.

  Outputs:
    --nocolor
      disable colored output.

  Filters:
    --ipv4, -4
      match only IPv4 addresses.
    --ipv6, -6
      match only IPv6 addresses.
    --exclude-reserved, -x
      exclude reserved/bogon IPs.
      full list can be found at https://ipinfo.io/bogon.
```

### Use the bulk API endpoint available from the CLI

The CLI also supports the bulk API endpoints. You can pass your IP address and receive bulk IP metadata enriched results in CSV, JSON, or YAML formats.

```
Usage: ipinfo bulk [<opts>] <ip | ip-range | cidr | filepath>

Description:
  Accepts IPs, IP ranges, CIDRs and file paths.

Examples:
  # Lookup all IPs from stdin ('-' can be implied).
  $ ipinfo prips 8.8.8.0/24 | ipinfo bulk
  $ ipinfo prips 8.8.8.0/24 | ipinfo bulk -

  # Lookup all IPs in 2 files.
  $ ipinfo bulk /path/to/iplist1.txt /path/to/iplist2.txt

  # Lookup all IPs from CIDR.
  $ ipinfo bulk 8.8.8.0/24

  # Lookup all IPs from multiple CIDRs.
  $ ipinfo bulk 8.8.8.0/24 8.8.2.0/24 8.8.1.0/24

  # Lookup all IPs in an IP range.
  $ ipinfo bulk 8.8.8.0-8.8.8.255

  # Lookup all IPs from multiple sources simultaneously.
  $ ipinfo bulk 8.8.8.0-8.8.8.255 1.1.1.0/30 123.123.123.123 ips.txt

Options:
  General:
    --token <tok>, -t <tok>
      use <tok> as API token.
    --nocache
      do not use the cache.
    --help, -h
      show help.

  Outputs:
    --field <field>, -f <field>
      lookup only specific fields in the output.
      field names correspond to JSON keys, e.g. 'hostname' or 'company.type'.
      multiple field names must be separated by commas.
    --nocolor
      disable colored output.

  Formats:
    --json, -j
      output JSON format. (default)
    --csv, -c
      output CSV format.
    --yaml, -y
      output YAML format.
```

### Use our free IP database

We have a [free IP to Country database](https://ipinfo.io/developers/ip-to-country-database). Take the time to explore it. Use the MMDB data type and utilize the CLI's MMDB command to enrich a nearly infinite amount of IP addresses.

https://ipinfo.io/developers/ip-to-country-database

```
ipinfo mmdb -h
Usage: ipinfo mmdb <cmd> [<opts>] [<args>]

Commands:
  read        read data for IPs in an mmdb file.
  import      import data in non-mmdb format into mmdb.
  export      export data from mmdb format into non-mmdb format.
  diff        see the difference between two mmdb files.
  metadata    print metadata from the mmdb file.
  verify      check that the mmdb file is not corrupted or invalid.
  completion  install or output shell auto-completion script.

Options:
  General:
    --nocolor
      disable colored output.
    --help, -h
      show help.
```

---

Links to explore:

- https://ipinfo.io/blog/ipinfo-database-formats/
- https://ipinfo.io/blog/nginx-for-access-control-and-privacy-policies/

Feel free to reach out to me anytime. Happy to help. Cheers!

**Comment by Dancha16** [comment]
Thank you so much for your valuable suggestions! I’ve carefully reviewed them and made the necessary adjustments. I’ve added the third parsing method using the IPinfo CLI’s grepip command. Your feedback helped me refine the solution, and the script is now more efficient and flexible.

If you have any more suggestions or spot anything else, feel free to let me know! Thanks again for your help!
